version: "3"
services:
  db:
    image: kartoza/postgis:13-3.1
    container_name: "postgres"
    environment:
      - POSTGRES_DB=freelas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=America/Sao_Paulo
    #volumes:
    # - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
